import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ryznoxy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/belajar-react/public/images1.png" />
      </head>
      <body className={inter.className}>
        <div className="h-screen">{children}</div>
      </body>
    </html>
  );
}
